[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pf3dxrd"              # Package name on PyPI
description = "processing scanning 3D X-ray diffraction data usinfg Friedel Pairs"
readme = "README.md"
authors = [
  { name = "Jean-Baptiste Jacob", email = "jean-baptiste.jacob@esrf.fr" }
]
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = [
  "concurrent.futures",
  "diffpy.structure",
  "Dans_Diffraction",
  "dill",
  "ImageD11",
  "multiprocessing",
  "orix",
  "scipy",
  "tqdm"
]

[project.urls]
Homepage = "https://github.com/jbjacob94/pf3dxrd/"
Documentation = "https://github.com/jbjacob94/pf3dxrd/blob/master/README.md"

[tool.setuptools.packages.find]
where = ["pf3dxrd"]
